### ISSUE TITLE
Game crash with Fabric API version 0.19.0+build.398 - Critical injection failure: LVT in MobEntity.getPreferredEquipmentSlot

### ISSUE THREAD

**Issue by Celesian** [Andrews54757/OptiFabric-updated#7]
My full log: https://paste.ee/p/0YFEp

Mods List: 

- fabric-api-0.19.0+build.398-1.16
- optifabric-updated-1.1.0-beta2-1.16.2
- preview_OptiFine_1.16.2_HD_U_G3_pre2

**Comment by Scorpion34** [comment]
the new api build just came out there's bound to be some issues with newer releases of the api temporary solution is just to use a previous version that and since the fabric-api-0.19.0+build.398-1.16 is a stable release optifabric-updated is still in beta I'm sure Andrew will find a solution :) (btw: I just use 0.17.2+build.396-1.16 and it works great never had better fps and 0 issues as far as I can tell.)

**Comment by Andrews54757** [comment]
Source of conflict:
https://github.com/FabricMC/fabric/commit/29679fd6fab0cc24161e86334cef99ab8f3cdf02#diff-6d838d7a40d24409eb638ed7814eb6a8R35-R43

**Comment by Andrews54757** [comment]
Fixed in https://github.com/Andrews54757/OptiFabric-updated/commit/6649d97a63487a95243076be50b938989dd39e3f.

**Comment by GaiaB0t** [comment]
should this be closed now?
